# This is a simple workflow to build a Hugo site and then deploy it on Firebase Hosting 

name: Set Hugo-On-Fire

# Triggers when any commit is pushed on Master
on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Fetch Hugo to Firebase docker image
    - uses: wajahatkarim3/Hugo-On-Fire@master
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    # Runs a single command using the runners shell
    # - name: Run a one-line script
      # run: echo Hello, world!

    # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
      # run: |
        # echo Add other actions to build,
        # echo test, and deploy your project.